config/routes.rb
Rails.application.routes.draw do
  if Rails.env.development?
    mount GraphiQL::Rails::Engine, at: "/graphiql", graphql_path: "/graphql"
  end

  post "/graphql", to: "graphql#execute"
  get "/s3/sign", to: "sign#sign"
  resources :anchors
  resources :bolts
  resources :climbing_routes do
    collection do
      post 'create_bolts'
    end
  end

  resources :bolt_ratings, :only => [:index]
  resources :areas

  root 'bolt_ratings#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/anchor.rb
class Anchor < ApplicationRecord
  belongs_to :climbing_route
end

app/controllers/anchors_controller.rb
class AnchorsController < ApplicationController
  before_action :set_anchor, only: [:show, :edit, :update, :destroy]

  # GET /anchors
  # GET /anchors.json
  def index
    @anchors = Anchor.all
  end

  # GET /anchors/1
  # GET /anchors/1.json
  def show
  end

  # GET /anchors/new
  def new
    @anchor = Anchor.new
  end

  # GET /anchors/1/edit
  def edit
  end

  # POST /anchors
  # POST /anchors.json
  def create
    @anchor = Anchor.new(anchor_params)

    respond_to do |format|
      if @anchor.save
        format.html { redirect_to @anchor, notice: 'Anchor was successfully created.' }
        format.json { render :show, status: :created, location: @anchor }
      else
        format.html { render :new }
        format.json { render json: @anchor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /anchors/1
  # PATCH/PUT /anchors/1.json
  def update
    respond_to do |format|
      if @anchor.update(anchor_params)
        format.html { redirect_to @anchor, notice: 'Anchor was successfully updated.' }
        format.json { render :show, status: :ok, location: @anchor }
      else
        format.html { render :edit }
        format.json { render json: @anchor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /anchors/1
  # DELETE /anchors/1.json
  def destroy
    @anchor.destroy
    respond_to do |format|
      format.html { redirect_to anchors_url, notice: 'Anchor was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_anchor
      @anchor = Anchor.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def anchor_params
      params.require(:anchor).permit(:number_of_bolts, :chain_type, :bolt_type, :year_placed, :climbing_route_id, :pitch)
    end
end

app/helpers/anchors_helper.rb
module AnchorsHelper
end

app/views/anchors/_form.html.erb
<%= form_with(model: anchor, local: true) do |form| %>
  <% if anchor.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(anchor.errors.count, "error") %> prohibited this anchor from being saved:</h2>

      <ul>
      <% anchor.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :number_of_bolts %>
    <%= form.number_field :number_of_bolts, id: :anchor_number_of_bolts %>
  </div>

  <div class="field">
    <%= form.label :chain_type %>
    <%= form.text_field :chain_type, id: :anchor_chain_type %>
  </div>

  <div class="field">
    <%= form.label :bolt_type %>
    <%= form.text_field :bolt_type, id: :anchor_bolt_type %>
  </div>

  <div class="field">
    <%= form.label :year_placed %>
    <%= form.number_field :year_placed, id: :anchor_year_placed %>
  </div>

  <div class="field">
    <%= form.label :climbing_route_id %>
    <%= form.text_field :climbing_route_id, id: :anchor_climbing_route_id %>
  </div>

  <div class="field">
    <%= form.label :pitch %>
    <%= form.number_field :pitch, id: :anchor_pitch %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/anchors/edit.html.erb
<h1>Editing Anchor</h1>

<%= render 'form', anchor: @anchor %>

<%= link_to 'Show', @anchor %> |
<%= link_to 'Back', anchors_path %>

app/views/anchors/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Anchors</h1>

<table>
  <thead>
    <tr>
      <th>Number of bolts</th>
      <th>Chain type</th>
      <th>Bolt type</th>
      <th>Year placed</th>
      <th>Climbing route</th>
      <th>Pitch</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @anchors.each do |anchor| %>
      <tr>
        <td><%= anchor.number_of_bolts %></td>
        <td><%= anchor.chain_type %></td>
        <td><%= anchor.bolt_type %></td>
        <td><%= anchor.year_placed %></td>
        <td><%= anchor.climbing_route %></td>
        <td><%= anchor.pitch %></td>
        <td><%= link_to 'Show', anchor %></td>
        <td><%= link_to 'Edit', edit_anchor_path(anchor) %></td>
        <td><%= link_to 'Destroy', anchor, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Anchor', new_anchor_path %>

app/views/anchors/new.html.erb
<h1>New Anchor</h1>

<%= render 'form', anchor: @anchor %>

<%= link_to 'Back', anchors_path %>

app/views/anchors/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Number of bolts:</strong>
  <%= @anchor.number_of_bolts %>
</p>

<p>
  <strong>Chain type:</strong>
  <%= @anchor.chain_type %>
</p>

<p>
  <strong>Bolt type:</strong>
  <%= @anchor.bolt_type %>
</p>

<p>
  <strong>Year placed:</strong>
  <%= @anchor.year_placed %>
</p>

<p>
  <strong>Climbing route:</strong>
  <%= @anchor.climbing_route %>
</p>

<p>
  <strong>Pitch:</strong>
  <%= @anchor.pitch %>
</p>

<%= link_to 'Edit', edit_anchor_path(@anchor) %> |
<%= link_to 'Back', anchors_path %>