config/routes.rb
Rails.application.routes.draw do
  if Rails.env.development?
    mount GraphiQL::Rails::Engine, at: "/graphiql", graphql_path: "/graphql"
  end

  post "/graphql", to: "graphql#execute"
  get "/s3/sign", to: "sign#sign"
  resources :anchors
  resources :bolts
  resources :climbing_routes do
    collection do
      post 'create_bolts'
    end
  end

  resources :bolt_ratings, :only => [:index]
  resources :areas

  root 'bolt_ratings#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/climbing_route.rb
class ClimbingRoute < ApplicationRecord
  belongs_to :area
  has_many :bolts
  has_many :anchors
end

app/controllers/climbing_routes_controller.rb
class ClimbingRoutesController < ApplicationController
  before_action :set_climbing_route, only: [:show, :edit, :update, :destroy]

  # GET /climbing_routes
  # GET /climbing_routes.json
  def index
    @climbing_routes = ClimbingRoute.all
  end

  # GET /climbing_routes/1
  # GET /climbing_routes/1.json
  def show
  end

  # GET /climbing_routes/new
  def new
    @climbing_route = ClimbingRoute.new
  end

  # GET /climbing_routes/1/edit
  def edit
  end

  # POST /climbing_routes
  # POST /climbing_routes.json
  def create
    @climbing_route = ClimbingRoute.new(climbing_route_params)

    respond_to do |format|
      if @climbing_route.save
        format.html { redirect_to @climbing_route, notice: 'Climbing route was successfully created.' }
        format.json { render :show, status: :created, location: @climbing_route }
      else
        format.html { render :new }
        format.json { render json: @climbing_route.errors, status: :unprocessable_entity }
      end
    end
  end

  def create_bolts
    incoming_route = ClimbingRoute.find(params["climbing route"].keys[0])
    params['Number of Bolts'].to_i.times do |n|
      Bolt.create!(number: (n+1), bolt_type: params["type of bolts used"], year_placed: params["year placed"], climbing_route: incoming_route)
    end
    redirect_to action: "show", id: params["climbing route"].keys[0]
  end

  # PATCH/PUT /climbing_routes/1
  # PATCH/PUT /climbing_routes/1.json
  def update
    respond_to do |format|
      if @climbing_route.update(climbing_route_params)
        format.html { redirect_to @climbing_route, notice: 'Climbing route was successfully updated.' }
        format.json { render :show, status: :ok, location: @climbing_route }
      else
        format.html { render :edit }
        format.json { render json: @climbing_route.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /climbing_routes/1
  # DELETE /climbing_routes/1.json
  def destroy
    @climbing_route.destroy
    respond_to do |format|
      format.html { redirect_to climbing_routes_url, notice: 'Climbing route was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_climbing_route
      @climbing_route = ClimbingRoute.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def climbing_route_params
      params.require(:climbing_route).permit(:name, :area_id, :protection_type, :pitches, :picture)
    end
end

app/helpers/climbing_routes_helper.rb
module ClimbingRoutesHelper
end

app/views/climbing_routes/_form.html.erb
<%= form_with(model: climbing_route, local: true) do |form| %>
  <% if climbing_route.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(climbing_route.errors.count, "error") %> prohibited this climbing_route from being saved:</h2>

      <ul>
      <% climbing_route.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :climbing_route_name %>
  </div>

  <div class="field">
    <%= form.label :area_id %>
    <%= form.text_field :area_id, id: :climbing_route_area_id %>
  </div>

  <div class="field">
    <%= form.label :protection_type %>
    <%= form.text_field :protection_type, id: :climbing_route_protection_type %>
  </div>

  <div class="field">
    <%= form.label :pitches %>
    <%= form.number_field :pitches, id: :climbing_route_pitches %>
  </div>

  <div class="field">
    <%= form.label :picture %>
    <%= form.text_field :picture, id: :climbing_route_picture %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/climbing_routes/edit.html.erb
<h1>Editing Climbing Route</h1>

<%= render 'form', climbing_route: @climbing_route %>

<%= link_to 'Show', @climbing_route %> |
<%= link_to 'Back', climbing_routes_path %>

app/views/climbing_routes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Climbing Routes</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Area</th>
      <th>Protection type</th>
      <th>Pitches</th>
      <th>Picture</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @climbing_routes.each do |climbing_route| %>
      <tr>
        <td><%= climbing_route.name %></td>
        <td><%= climbing_route.area %></td>
        <td><%= climbing_route.protection_type %></td>
        <td><%= climbing_route.pitches %></td>
        <td><%= climbing_route.picture %></td>
        <td><%= link_to 'Show', climbing_route %></td>
        <td><%= link_to 'Edit', edit_climbing_route_path(climbing_route) %></td>
        <td><%= link_to 'Destroy', climbing_route, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Climbing Route', new_climbing_route_path %>

app/views/climbing_routes/new.html.erb
<h1>New Climbing Route</h1>

<%= render 'form', climbing_route: @climbing_route %>

<%= link_to 'Back', climbing_routes_path %>

app/views/climbing_routes/show.html.erb
<p id="notice"><%= notice %></p>
<h1><%= @climbing_route.name %></h1>
<p>
  <strong>Area:</strong>
  <%= @climbing_route.area.name %>
</p>

<p>
  <strong>Protection type:</strong>
  <%= @climbing_route.protection_type %>
</p>

<p>
  <strong>Pitches:</strong>
  <%= @climbing_route.pitches %>
</p>

<% if @climbing_route.bolts.present? %>
<h1>Bolts</h1>

<table>
  <thead>
    <tr>
      <th>Number</th>
      <th>Bolt type</th>
      <th>Year placed</th>
      <th>Pitch</th>
      <th colspan="1"></th>
      <th>Flag as a problem</th>
    </tr>
  </thead>

  <tbody>
    <% @climbing_route.bolts.each do |bolt| %>
      <tr>
        <td><%= bolt.number %></td>
        <td><%= bolt.bolt_type %></td>
        <td><%= bolt.year_placed %></td>
        <td><%= bolt.pitch %></td>
        <td><%= link_to 'Destroy', bolt, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <td><input type="checkbox"/></td>
      </tr>
    <% end %>
  </tbody>
</table>
<% else %>
  <%= form_tag( {:controller => 'climbing_routes', :action => 'create_bolts'}, :method => 'post' ) do |f| %>
    <%= number_field_tag("Number of Bolts") %>
    <%= text_field_tag("type of bolts used") %>
    <%= text_field_tag("year placed", DateTime.now.year) %>
    <%= hidden_field("climbing route", @climbing_route.id) %>
  <%= submit_tag('generate bolts') %>
<% end %>
<% end %>