config/routes.rb
Rails.application.routes.draw do
  if Rails.env.development?
    mount GraphiQL::Rails::Engine, at: "/graphiql", graphql_path: "/graphql"
  end

  post "/graphql", to: "graphql#execute"
  get "/s3/sign", to: "sign#sign"
  resources :anchors
  resources :bolts
  resources :climbing_routes do
    collection do
      post 'create_bolts'
    end
  end

  resources :bolt_ratings, :only => [:index]
  resources :areas

  root 'bolt_ratings#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/bolt.rb
class Bolt < ApplicationRecord
  belongs_to :climbing_route
end

app/controllers/bolts_controller.rb
class BoltsController < ApplicationController
  before_action :set_bolt, only: [:show, :edit, :update, :destroy]

  # GET /bolts
  # GET /bolts.json
  def index
    @bolts = Bolt.all
  end

  # GET /bolts/1
  # GET /bolts/1.json
  def show
  end

  # GET /bolts/new
  def new
    @bolt = Bolt.new
  end

  # GET /bolts/1/edit
  def edit
  end

  # POST /bolts
  # POST /bolts.json
  def create
    if bolt_params.number_of_bolts
      #not what we want
    else
    @bolt = Bolt.new(bolt_params)
    end
    respond_to do |format|
      if @bolt.save
        format.html { redirect_to @bolt, notice: 'Bolt was successfully created.' }
        format.json { render :show, status: :created, location: @bolt }
      else
        format.html { render :new }
        format.json { render json: @bolt.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bolts/1
  # PATCH/PUT /bolts/1.json
  def update
    respond_to do |format|
      if @bolt.update(bolt_params)
        format.html { redirect_to @bolt, notice: 'Bolt was successfully updated.' }
        format.json { render :show, status: :ok, location: @bolt }
      else
        format.html { render :edit }
        format.json { render json: @bolt.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bolts/1
  # DELETE /bolts/1.json
  def destroy
    @bolt.destroy
    respond_to do |format|
      format.html { redirect_to bolts_url, notice: 'Bolt was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_bolt
      @bolt = Bolt.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def bolt_params
      params.require(:bolt).permit(:number, :bolt_type, :year_placed, :climbing_route_id, :pitch)
    end
end

app/helpers/bolts_helper.rb
module BoltsHelper
end

app/views/bolts/_form.html.erb
<%= form_with(model: bolt, local: true) do |form| %>
  <% if bolt.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(bolt.errors.count, "error") %> prohibited this bolt from being saved:</h2>

      <ul>
      <% bolt.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :number %>
    <%= form.number_field :number, id: :bolt_number %>
  </div>

  <div class="field">
    <%= form.label :bolt_type %>
    <%= form.text_field :bolt_type, id: :bolt_bolt_type %>
  </div>

  <div class="field">
    <%= form.label :year_placed %>
    <%= form.number_field :year_placed, id: :bolt_year_placed %>
  </div>

  <div class="field">
    <%= form.label :climbing_route_id %>
    <%= form.text_field :climbing_route_id, id: :bolt_climbing_route_id %>
  </div>

  <div class="field">
    <%= form.label :pitch %>
    <%= form.number_field :pitch, id: :bolt_pitch %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/bolts/edit.html.erb
<h1>Editing Bolt</h1>

<%= render 'form', bolt: @bolt %>

<%= link_to 'Show', @bolt %> |
<%= link_to 'Back', bolts_path %>

app/views/bolts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Bolts</h1>

<table>
  <thead>
    <tr>
      <th>Number</th>
      <th>Bolt type</th>
      <th>Year placed</th>
      <th>Climbing route</th>
      <th>Pitch</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @bolts.each do |bolt| %>
      <tr>
        <td><%= bolt.number %></td>
        <td><%= bolt.bolt_type %></td>
        <td><%= bolt.year_placed %></td>
        <td><%= bolt.climbing_route %></td>
        <td><%= bolt.pitch %></td>
        <td><%= link_to 'Show', bolt %></td>
        <td><%= link_to 'Edit', edit_bolt_path(bolt) %></td>
        <td><%= link_to 'Destroy', bolt, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Bolt', new_bolt_path %>

app/views/bolts/new.html.erb
<h1>New Bolt</h1>

<%= render 'form', bolt: @bolt %>

<%= link_to 'Back', bolts_path %>

app/views/bolts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Number:</strong>
  <%= @bolt.number %>
</p>

<p>
  <strong>Bolt type:</strong>
  <%= @bolt.bolt_type %>
</p>

<p>
  <strong>Year placed:</strong>
  <%= @bolt.year_placed %>
</p>

<p>
  <strong>Climbing route:</strong>
  <%= @bolt.climbing_route %>
</p>

<p>
  <strong>Pitch:</strong>
  <%= @bolt.pitch %>
</p>

<%= link_to 'Edit', edit_bolt_path(@bolt) %> |
<%= link_to 'Back', bolts_path %>